naiveOLS = lm(log(loss) ~ .-id, data = pml.train)
naiveOLS$xlevels[["cat75"]] = union(naiveOLS$xlevels[["cat75"]], levels(pml.test$cat75))
naiveOLS$xlevels[["cat89"]] = union(naiveOLS$xlevels[["cat89"]], levels(pml.test$cat89))
naiveOLS$xlevels[["cat92"]] = union(naiveOLS$xlevels[["cat92"]], levels(pml.test$cat92))
naiveOLS$xlevels[["cat99"]] = union(naiveOLS$xlevels[["cat99"]], levels(pml.test$cat99))
naiveOLS$xlevels[["cat101"]] = union(naiveOLS$xlevels[["cat101"]], levels(pml.test$cat101))
naiveOLS$xlevels[["cat102"]] = union(naiveOLS$xlevels[["cat102"]], levels(pml.test$cat102))
naiveOLS$xlevels[["cat103"]] = union(naiveOLS$xlevels[["cat103"]], levels(pml.test$cat103))
naiveOLS$xlevels[["cat105"]] = union(naiveOLS$xlevels[["cat105"]], levels(pml.test$cat105))
naiveOLS$xlevels[["cat107"]] = union(naiveOLS$xlevels[["cat107"]], levels(pml.test$cat107))
naiveOLS$xlevels[["cat109"]] = union(naiveOLS$xlevels[["cat109"]], levels(pml.test$cat109))
naiveOLS$xlevels[["cat110"]] = union(naiveOLS$xlevels[["cat110"]], levels(pml.test$cat110))
naiveOLS$xlevels[["cat113"]] = union(naiveOLS$xlevels[["cat113"]], levels(pml.test$cat113))
naiveOLS$xlevels[["cat114"]] = union(naiveOLS$xlevels[["cat114"]], levels(pml.test$cat114))
naiveOLS$xlevels[["cat116"]] = union(naiveOLS$xlevels[["cat116"]], levels(pml.test$cat116))
naivePred = exp(predict(naiveOLS, newdata = pml.test))
submission$loss = naivePred
write.csv(submission, file = "submission.csv", row.names = FALSE)
trollPred = median(pml.train$loss)
trollPred2 = mean(pml.train$loss)
submission$loss = trollPred2
